version: "3.1"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=docker
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - "3308:3306"
  web:
    build: docker/php-apache2
    container_name: web
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"